### ISSUE TITLE
Update offline status (toggle + new logic tracking)

### ISSUE THREAD

**Issue by Kilian-Perisset** [Infomaniak/android-kDrive#69]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/7050479/122249204-ef63ac80-cec8-11eb-8fbc-b119c33f71b8.png">

- [x] The "available offline toggle" must be refreshed adequately after defining a file as offline. 
and if we click back on the toggle, the local file must be deleted.
- [x] View pending offline files that will be downloaded
- [x] New logic tracking
